# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edef2ae1c6c6f66f87194a15aff0d4533bc702226248c13d816e73dda02e244f57b7b662c7cf0871264bf6377e509f338778644fde4699b2c4e7b5ef7648fc33
  stripe_public_key: pk_test_EyeUHT5ZVqLa37nb5P7J0caA

test:
  secret_key_base: 1c71350d36f27b1dbac231cdf98a6573ee230349f316e69b0e92b118af008da9b0dc398504107d6770864e2ee8478a5c9b0c4f95adc429fe8e9f81e9f48cd1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>
